{% set version = "0.11rc1" %}

package:
  name: movingpandas
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/movingpandas/movingpandas-{{ version }}.tar.gz
  sha256: bd37ff690bd4b5fef54d16a41c1d021d4e6453548b0da32c22665a650625a51e

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - pandas
    - shapely
    - geopandas
    - matplotlib-base
    - hvplot
    - bokeh
    - cartopy
    - geoviews
    - pyproj
    - geopy

test:
  imports:
    - movingpandas

about:
  home: https://github.com/anitagraser/movingpandas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'MovingPandas implements Trajectory classes and corresponding methods based on GeoPandas'

extra:
  recipe-maintainers:
    - anitagraser
    - jorisvandenbossche
