{% set version = "0.3rc1" %}

package:
  name: movingpandas
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/movingpandas/movingpandas-{{ version }}.tar.gz
  sha256: 53104db32cb6bca165762582878d7cc568e44733441c82b7f0e1a6b0fd4b4f70

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - pandas
    - shapely
    - geopandas
    - matplotlib-base
    - hvplot
    - bokeh<2.0
    - cartopy
    - geoviews
    - pyproj

test:
  imports:
    - movingpandas

about:
  home: https://github.com/anitagraser/movingpandas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Implementation of Trajectory classes and functions built on top of GeoPandas'

extra:
  recipe-maintainers:
    - anitagraser
    - jorisvandenbossche
