{% set version = "0.13rc1" %}

package:
  name: movingpandas
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/movingpandas/movingpandas-{{ version }}.tar.gz
  sha256: a975312250d2b50d9ed85fa2817276103d98183421ac4bbbf8752bba053900d6

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fiona
    - geopandas-base
    - geopy
    - matplotlib-base    
    - numpy
    - pandas
    - rtree
    - shapely

test:
  imports:
    - movingpandas

about:
  home: https://github.com/anitagraser/movingpandas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'MovingPandas implements Trajectory classes and corresponding methods based on GeoPandas'

extra:
  recipe-maintainers:
    - anitagraser
    - jorisvandenbossche
