{% set version = "0.6rc1" %}

package:
  name: movingpandas
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/movingpandas/movingpandas-{{ version }}.tar.gz
  sha256: f492692efde002aeb3030baed9175a85cf8f10556d4cd25c9e8dfe3a5acfe6a8

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - pandas
    - shapely
    - geopandas
    - matplotlib-base
    - hvplot
    - bokeh
    - cartopy
    - geoviews
    - pyproj
    - geopy

test:
  imports:
    - movingpandas

about:
  home: https://github.com/anitagraser/movingpandas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'MovingPandas implements Trajectory classes and corresponding methods based on GeoPandas'

extra:
  recipe-maintainers:
    - anitagraser
    - jorisvandenbossche
