{% set name = "movingpandas" %}
{% set version = "0.22.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: ed171d260444ed1a787b51a7c745805dc37fa4721487dd4766118a97d49b94f6
  - url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 44df0999699c5977267a8ff76856b238d457e17a8cd76d08c090e1cdb81d0219
    folder: gh_src

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - geopandas-base
    # our geopandas-base includes already fiona
    # see https://github.com/AnacondaRecipes/geopandas-feedstock/blob/db3ee7c59204c6ec5e797f6c208339e87ece8783/recipe/meta.yaml#L32
    # - fiona
    - geopy
    - matplotlib-base

test:
  source_files:
    - gh_src/movingpandas/tests/mftrajectory.json
    - gh_src/movingpandas/tests/movingfeatures_collection.json
    - gh_src/movingpandas/tests/movingfeatures.json
  imports:
    - movingpandas
    - movingpandas.geometry_utils
    - movingpandas.io
    - movingpandas.overlay
    - movingpandas.point_clusterer
    - movingpandas.tools._show_versions
    - movingpandas.tools._warnings
    - movingpandas.trajectory
    - movingpandas.trajectory_aggregator
    - movingpandas.trajectory_cleaner
    - movingpandas.trajectory_collection
    - movingpandas.trajectory_generalizer
    - movingpandas.trajectory_plotter
    - movingpandas.trajectory_splitter
    - movingpandas.trajectory_stop_detector
    - movingpandas.unit_utils
  commands:
    - pip check
    - cp gh_src/movingpandas/tests/*.json ${SP_DIR}/movingpandas/tests  # [unix]
    - cp gh_src/movingpandas/tests/*.json %SP_DIR%/movingpandas/tests  # [win]
    - pytest --pyargs movingpandas.tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/movingpandas/movingpandas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: MovingPandas implements Trajectory classes and corresponding methods based on GeoPandas.
  description: MovingPandas implements trajectory classes and functions built on top of GeoPandas.
  doc_url: https://movingpandas.readthedocs.io
  dev_url: https://github.com/movingpandas/movingpandas

extra:
  recipe-maintainers:
    - raybellwaves
    - anitagraser
    - jorisvandenbossche
