{% set name = "movingpandas" %}
{% set version = "0.17.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a84bab2473a0ee254ac10bd562b4c4c955ea69820a033be0220abd4cd2476c6e
  patches:
    - patches/0001-fix-long-description-utf-8.patch  # [win]

build:
  number: 0
  # fiona, rtree not available for s390x
  skip: true  # [py<38 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - m2-patch    # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - fiona
    - geopandas-base
    - geopy
    - matplotlib-base
    - rtree

# skip these tests because they depend on json files not in the tarball
{% set tests_to_skip = "test_mf_file" %}
{% set tests_to_skip = tests_to_skip + " or test_mf_collection_file" %}
{% set tests_to_skip = tests_to_skip + " or test_mf_collection_needs_id" %}
{% set tests_to_skip = tests_to_skip + " or test_wrong_property_raises_error" %}
{% set tests_to_skip = tests_to_skip + " or test_gdf_to_mf_json" %}
{% set tests_to_skip = tests_to_skip + " or test_outlier_cleaner" %}
# skip this test on win, it requires tk
{% set tests_to_skip = tests_to_skip + " or test_plot_does_not_alter_df" %}  # [win]
# skip this test on win, it requires tcl
{% set tests_to_skip = tests_to_skip + " or test_support_for_other_time_column_names" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_plot_exists" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_plot_speed_not_altering_collection" %}  # [win]

test:
  imports:
    - movingpandas
  requires:
    - pip
    - pytest
  source_files:
    - movingpandas/tests
  commands:
    - pip check
    - pytest -v -r s -k "not({{ tests_to_skip }})" movingpandas/tests/

about:
  home: https://github.com/movingpandas/movingpandas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: MovingPandas implements Trajectory classes and corresponding methods based on GeoPandas.
  description: MovingPandas implements trajectory classes and functions built on top of GeoPandas.
  doc_url: https://movingpandas.readthedocs.io/
  dev_url: https://github.com/movingpandas/movingpandas

extra:
  recipe-maintainers:
    - raybellwaves
    - anitagraser
    - jorisvandenbossche
