travis:
  secure:
    BINSTAR_TOKEN: Uoxe+C6VUwgevYmEUjt23xkYIC3eQ5681OZ6d34GRd7aU9+q8DJO9kpuT61pdk3BfWtIdrzdZ2PT7hMP1kwsRfP/RGoso9NKFff3m7LKaQv0xjMAy9cgAtY4I6T8EdwlaqMStZYCU2ruAG04EjMGdn/oH/WQ9NruRiuiNpGs3ZRfduodJU2oaXqVekIHAjQXFsFN0cLbZ1CP/hEOPCjKMmzRfQHNlqYwHw66PleSrc+GBQEaFuOjyz+gZUPYY6v4uz3Sd4wxYP0A5nXkD/oFHXOTaN3KYN1G+iU2XiaMO6HyatdI95/2eq9FrerGKcDCj3GEt1IvJvqjY1LKq4NdswzHhZrIOovrfFA1zxOVIGec3ETg/J2MMWH8QyGdAH7512L8pgEK/WeYc91I5IohBO72O0hVwIkvSyubHM2DOWBiwH4C+84EdOI6lJ5WE3p/RlAw/j/sZ7RZeU1LBy6eGnSJDu2ikTWe5p/di+jEVAeU5W10Tl1WwbW7KKnFs9V+dMu1UVXquKsk7pD7PtWr6FlE/Thl3yfhyCzrzwEZ6idnTkZY11liMbGiE4tIh8XMmYcyVjOPaMVKaODX+xgxR1judDAAxSEgq9Itd22FrzghUmyzVXa1E3oQkYMrkuAIv1hN0R7J8ZG+6UuFkFUi4extxEllF9ZCCJzXtxqPLjM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
