travis:
  secure:
    BINSTAR_TOKEN: U+u8sDL1j9Oo4H56jZQPGnbRnWkhcKZnMuP2HEon8osBR4qemthnHMfU1DAkgpnimzccqtFXAnxEauj8+IxgvV4YmkRgnK/C58UbpvO8u92p9mE6BYrPEGRr431DghUx1Sr/0duB6JoN3UafVPlebVy1R4xMgLLY+VBamKI1E5S4iQTGzcva39OycgvtcGgHZpV8+Y7w0zYjmr62uqIytbY/JGHlY2IWcegQe3yrhJk4LByAFGjMUCrHzdD274jiryPn0HD+iP8VDcK6rnJd4tOWWDyoxwWulwxpW55QfraUEkOIcf7M6+neONcBG8mYpy7FNHi/4JTqa3KacBZ+NT9Akgmnj+X4/71xL/0viQ0sYcU5gyACndsylIZjmUP4EGCZyuAo4q1HQrr0h0rcdf/jCIgR9vFy0INqB2H7PIKXY6b6dRmlbbe8p4I9jUU2zRjJaQM4oNJHh6ziaM8RvIZEVu+WT26UbGbu6epQ3LERpdgt/scM3K849XiTguEILTYYBZtp8InrHiGBRVH2U92F86BmomseHpXs3l3nLsUkZrGMqA2h+v9mIH1a6kZ0TGFHNWukBkbnd1Q78DYOdmedsIiHQzfMhnh2FvsthEHMM3VTQ0kRH9aSXELKpBGXoY8hziv8fefmgqo5D+yy4/w+ZNY6U6GS8xKCerMBM84=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
